apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ .Release.Name }}-deployment
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort | int }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort | int }}
